name: Ba-dua Report

on:
  push:
   branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8


    steps:
    - uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'adopt'
    - name: Build and Test with Maven
      run: mvn -T 1.5C clean verify -P badua-profile -e -X
    - name: Archive badua coverage results
      uses: actions/upload-artifact@v3
      with:
        name: badua-coverage-report
        path: bookkeeper-server/target/baduaReport.xml
        if-no-files-found: error
