name: Maven Clean Test

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: docker://fedora:latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
        uses: actions/setup-java@v3.10.0
        with: 
              java-version: '1.8'
              distribution: 'adopt'
              cache: maven
    - name: Build and Test with Maven
      run: mvn clean test
